"use client";
import { use, useCallback, useEffect, useState } from "react";
import { adminVideoApi, type AdminVideoDetail } from "@/features/video/api/adminVideoApi";
import { mediaProcessingApi } from "@/features/media-processing/api/mediaProcessingApi";
import { videoUploadApi, type UploadStatusResponse } from "@/features/video-upload/api/videoUploadApi";
import { ProgressBar, StatusBadge } from "@/shared/components/StatusBadge";
import { userError } from "@/shared/lib/apiClient";
export default function VideoDetailPage({ params }: { params: Promise<{ videoId: string }> }) {
  const { videoId } = use(params); const id = Number(videoId);
  const [video, setVideo] = useState<AdminVideoDetail | null>(null); const [upload, setUpload] = useState<UploadStatusResponse | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { try { const result = await adminVideoApi.getVideo(id); setVideo(result); setError(""); if (result.source?.videoFileId) setUpload(await videoUploadApi.status(result.source.videoFileId)); } catch (reason) { setError(userError(reason)); } }, [id]);
  useEffect(() => { const timer = setTimeout(() => void refresh(), 0); return () => clearTimeout(timer); }, [refresh]);
  useEffect(() => {
    const status = video?.processing?.status;
    if (!status || !["PROCESSING", "QUEUED", "RETRY_WAIT"].includes(status)) return;
    const interval = setInterval(() => { if (!document.hidden) void refresh(); }, status === "PROCESSING" ? 3000 : 5000);
    const onVisible = () => { if (!document.hidden) void refresh(); };
    document.addEventListener("visibilitychange", onVisible);
    return () => { clearInterval(interval); document.removeEventListener("visibilitychange", onVisible); };
  }, [video?.processing?.status, refresh]);
  async function retry() { if (!video?.processing) return; setBusy(true); try { await mediaProcessingApi.retry(video.processing.jobId); await refresh(); } catch (reason) { setError(userError(reason)); } finally { setBusy(false); } }
  if (!Number.isSafeInteger(id) || id < 1) return <p className="error">유효하지 않은 Video ID입니다.</p>;
  return <><div className="page-heading"><div><span className="eyebrow">VIDEO DETAIL / #{id}</span><h1>{video?.title ?? "영상 상세"}</h1><p>원본 업로드와 HLS 처리 상태</p></div><button className="button" onClick={() => void refresh()}>새로고침</button></div>{error && <div className="panel error" role="alert">{error} <button className="button small" onClick={() => void refresh()}>다시 시도</button></div>}{!video && !error && <p className="muted">영상 정보를 불러오는 중입니다…</p>}{video && <><div className="detail-grid"><section className="panel"><span className="eyebrow">VIDEO</span><div className="thumbnail large">THUMBNAIL<br/>NOT AVAILABLE</div><h2>{video.title}</h2><div className="kv"><span>Video ID</span><strong>{video.id}</strong><span>상태</span><StatusBadge value={video.status} /></div></section><section className="panel"><span className="eyebrow">SOURCE UPLOAD</span><h2>원본 파일</h2><div className="kv"><span>VideoFile ID</span><strong>{video.source?.videoFileId ?? "—"}</strong><span>업로드 상태</span><strong>{video.source && <StatusBadge value={video.source.status} />}</strong><span>확인된 파트</span><strong>{upload ? `${upload.confirmedParts.length} / ${upload.totalParts}` : "—"}</strong></div>{upload && <ProgressBar value={upload.totalParts ? upload.confirmedParts.length / upload.totalParts * 100 : 0} label="확인된 업로드 파트" />}</section><section className="panel"><span className="eyebrow">MEDIA PROCESSING</span><h2>HLS 작업</h2>{video.processing ? <><div className="kv"><span>Job ID</span><strong>{video.processing.jobId}</strong><span>상태</span><StatusBadge value={video.processing.status} /><span>단계</span><strong>{video.processing.stage}</strong><span>시도</span><strong>{video.processing.attempt}</strong><span>오류 코드</span><strong>{video.processing.errorCode ?? "—"}</strong></div><ProgressBar value={video.processing.progressPercent} label="HLS 예상 처리 진행률" /><p className="muted">예상 처리 진행률 {video.processing.progressPercent}%</p>{video.processing.status === "FAILED" && <button className="button primary" disabled={busy} onClick={() => void retry()}>{busy ? "처리 중…" : "다시 처리"}</button>}</> : <p className="muted">생성된 처리 작업이 없습니다.</p>}</section><section className="panel"><span className="eyebrow">PACKAGE</span><h2>게시 패키지</h2><div className="kv"><span>Package ID</span><strong>{video.mediaPackage?.id ?? "—"}</strong><span>Profile</span><strong>{video.mediaPackage?.profileVersion ?? "—"}</strong><span>상태</span><strong>{video.mediaPackage ? "READY" : "대기"}</strong></div></section></div><section className="panel"><span className="eyebrow">WORKFLOW · 현재 상태 기반</span><h2>영상 처리 흐름</h2><div className="workflow">{["영상 생성", "원본 업로드", "Source Object", "HLS Job", "FFmpeg", "Package Validation", "READY"].map((step, index) => <span key={step} className={(index === 0 || index <= 2 && video.source?.status === "COMPLETED" || index >= 3 && index <= 5 && video.processing?.status === "COMPLETED" || index === 6 && video.status === "READY") ? "done" : ""}>{step}</span>)}</div></section></>}</>;
}
